Viljaladu-Hollat/Controllers/AutoDatasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Viljaladu_Hollat.Models;

namespace Viljaladu_Hollat.Controllers
{
    public class AutoDatasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AutoDatas
        public ActionResult Index()
        {
            return View(db.AutoDatas.ToList());
        }
        public ActionResult ViljaladuAndmed()
        {
            return View(db.AutoDatas.ToList());
        }

        // GET: AutoDatas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AutoData autoData = db.AutoDatas.Find(id);
            if (autoData == null)
            {
                return HttpNotFound();
            }
            return View(autoData);
        }

        public ActionResult Import()
        {
            return View("ViljaladuAndmed");
        }

        public ActionResult Export()
        {
            return View();
        }


        // GET: AutoDatas/Create
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult LisaAndmed()
        {
            return View();
        }

        // POST: AutoDatas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,autonr,sisenemismass,lahkumismass")] AutoData autoData)
        {
            if (ModelState.IsValid)
            {
                db.AutoDatas.Add(autoData);
                db.SaveChanges();
                return RedirectToAction("index");
            }

            return View(autoData);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LisaAndmed([Bind(Include = "id,autonr,sisenemismass,lahkumismass")] AutoData autoData)
        {
            if (ModelState.IsValid)
            {
                db.AutoDatas.Add(autoData);
                db.SaveChanges();
                return RedirectToAction("ViljaladuAndmed");
            }

            return View(autoData);
        }


        // GET: AutoDatas/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AutoData autoData = db.AutoDatas.Find(id);
            if (autoData == null)
            {
                return HttpNotFound();
            }
            return View(autoData);
        }

        // POST: AutoDatas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,autonr,sisenemismass,lahkumismass")] AutoData autoData)
        {
            if (ModelState.IsValid)
            {
                db.Entry(autoData).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(autoData);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Export([Bind(Include = "id,autonr,sisenemismass,lahkumismass")] AutoData autoData)
        {
            if (ModelState.IsValid)
            {
                db.Entry(autoData).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ViljaladuAndmed");
            }
            return View(autoData);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Import([Bind(Include = "id,autonr,sisenemismass,lahkumismass")] AutoData autoData)
        {
            if (ModelState.IsValid)
            {
                db.Entry(autoData).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ViljaladuAndmed");
            }
            return View(autoData);
        }

        // GET: AutoDatas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AutoData autoData = db.AutoDatas.Find(id);
            if (autoData == null)
            {
                return HttpNotFound();
            }
            return View(autoData);
        }
        [Authorize]
        public ActionResult Delete2(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AutoData autoData = db.AutoDatas.Find(id);
            if (autoData == null)
            {
                return HttpNotFound();
            }
            return View(autoData);
        }

        [HttpPost, ActionName("Delete2")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete2Confirmed(int id)
        {
            AutoData autoData = db.AutoDatas.Find(id);
            db.AutoDatas.Remove(autoData);
            db.SaveChanges();
            return RedirectToAction("ViljaladuAndmed");
        }
        // POST: AutoDatas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AutoData autoData = db.AutoDatas.Find(id);
            db.AutoDatas.Remove(autoData);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Viljaladu-Hollat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img class="pilt" src="https://www.pinclipart.com/picdir/middle/98-983024_clipart-vegetables-leafy-vegetable-vegetable-logo-png-download.png"/>
                @Html.ActionLink("Viljaladu", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Andmed", "ViljaladuAndmed", "AutoDatas")</li>
                    <li>@Html.ActionLink("Import", "LisaAndmed", "AutoDatas")</li>
                    <li>@Html.ActionLink("Export", "Export", "AutoDatas")</li>
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>